in:
  type: jira
  username: 'USERNAME'
  password: 'PASSWORD'
  uri: 'https://treasure-data.atlassian.net'
  # oauth_token:
  # oauth_secret:
  attributes:
    summary: string
    project: string
  jql: "summary ~ P"
out:
  type: stdout
exec: {}
